### ISSUE TITLE
How to handle cases where siblings affect layout

### ISSUE THREAD

**Issue by jakearchibald** [chrishtr/display-locking#19]
Thinking of things like grid, table cells, floats, or even just wrapping.

Eg:

```html
<style>
.content {
  contain: content;
  background: yellow;
}
</style>
<div class="float">H</div>
<div class="content">ello</div>
<script>
(async function() {
  await querySelector('.content').getDisplayLock().acquire();
  document.querySelector('.float').style.float = 'left';
})();
</script>
```

What would happen in the above case?

http://jsbin.com/qikitoc/1/edit?html,css,output.

**Comment by chrishtr** [comment]
I think you're asking about what happens when the element that is locked is moved around or changes
size. Is that correct?

When an element is locked for display and the element is already in the DOM, the subtree is what is actually locked, not the element itself. So if you change the element's size, its border box decorations or other self-attributes like border-radius clip filter etc are adjusted. but the subtree content's pixels stay the same, because they are not yet resized to match. This is "mode 1" in the parlance of #12.

And if the element is moved, so is the content below it moves also.

For example, if you have a contain:content element with a border, then the subtree will be painted and clipped to that size. If, while the element is locked, you resize the element somehow, then the border will change size but the subtree will still be clipped and drawn to the old size.

**Comment by jakearchibald** [comment]
> When an element is locked for display and the element is already in the DOM, the subtree is what is actually locked, not the element itself.

Ahh, that's the bit I didn't realise. Happy for this to close.

**Comment by chrishtr** [comment]
> Ahh, that's the bit I didn't realise. Happy for this to close.

Cool. I didn't understand that very well either until seeing a bunch of examples. I think once
we have better canonical examples built it will become more clear.

**Comment by jakearchibald** [comment]
Maybe the API could be named in a way that suggests the locking applies to the content?
